# pyproject.toml
[project]
name = "SDelighTex"
version = "0.1.0"
description = '''
Advanced Geometry Enhancement for High-Resolution 3D Modeling
'''

[build-system]
requires = [
    "setuptools>=42",
    "click",
    "tqdm"
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
exclude = ["tests*"]

[project.scripts]
dt-delight = "sdelightex.scripts.stable_delight:main"
dt-texture = "sdelightex.scripts.texture_mesh:main"
